// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarvedRock.Data.Migrations
{
    [DbContext(typeof(LocalContext))]
    [Migration("20241125072906_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CarvedRock.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "boots",
                            Description = "Great support in this high-top to take you to great heights and trails.",
                            ImgUrl = "https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/img-brownboots.jpg",
                            Name = "Trailblazer",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            Id = 2,
                            Category = "boots",
                            Description = "Easy in and out with this lightweight but rugged shoe with great ventilation to get your around shores, beaches, and boats.",
                            ImgUrl = "https://www.pluralsight.com/content/dam/pluralsight2/teach/author-tools/carved-rock-fitness/img-greyboots.jpg",
                            Name = "Coastliner",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            Id = 3,
                            Category = "boots",
                            Description = "All the insulation and support you need when wandering the rugged trails of the woods and backcountry.",
                            ImgUrl = "/images/shutterstock_222721876.jpg",
                            Name = "Woodsman",
                            Price = 64.989999999999995
                        },
                        new
                        {
                            Id = 4,
                            Category = "boots",
                            Description = "Get up and down rocky terrain like a billy-goat with these awesome high-top boots with outstanding support.",
                            ImgUrl = "/images/shutterstock_475046062.jpg",
                            Name = "Billy",
                            Price = 79.989999999999995
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
